spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect
        jdbc:
          time_zone: Asia/Seoul
        use_sql_comments: true
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      maxFileSize: 50MB
      maxRequestSize: 50MB
  main:
    allow-bean-definition-overriding: true
  datasource:
    password: KD_V2vbNGt
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sa
    url: jdbc:sqlserver://112.146.206.134:1433;databaseName=jin_test1;;encrypt=true;trustServerCertificate=true;
  data:
    redis:
      port: 6379
      host: localhost
      password: asdf
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
        SQL: DEBUG
      springframework:
        jdbc:
          core: DEBUG
        nodeValue: DEBUG
    web: debug
    sql: debug
upload:
  path: files/file
server:
  port: 8080
